/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleproject1;

import javax.swing.JOptionPane;

public class App {
    public String highAndLow() {
        String texto=JOptionPane.showInputDialog("Numeros:");
        String numEnTex[]=texto.split(" ");
        int n=numEnTex.length;
        int numero[]=new int [n];
        for (int i=0; i<n;i++){
            numero[i]=Integer.parseInt(numEnTex[i]);
        }
        int mayor=numero[1];
        int menor=numero[1];
        for(int i=0;i<n;i++){
           if (numero[i]>mayor){
               mayor=numero[i];
           }
           if(numero[i]<menor){
               menor=numero[i];
           }
        }
        System.out.println(mayor+" "+menor);
        return " ";
    }

    public static void main(String[] args) {
        System.out.println(new App().highAndLow());
    }
}
