/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multiples;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        Scanner numero = new Scanner(System.in);
        System.out.println("Ingresar un numero entero para hallar los multiplos de 3 y 5");
        int numint = numero.nextInt();

        int three = 0;
        int five = 0;
        if (numint >= 0) {
            for (int i = 0; i < numint; i++) {
                if (i % 3 == 0 && i != 0) {
                    // System.out.println(i + " multiplo de 3");
                    three = three + i;
                } else {
                    if (i % 5 == 0 && i != 0) {
                        // System.out.println(i + " multiplo de 5");
                        five = five + i;
                    }
                }
            }
            System.out.print("La suma de los multiplos de 3 y 5 menores al numero ingresado es: ");
            System.out.println(three + five);
        }
    }
}
