/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package phonenumber;

import java.util.Arrays;
import java.util.Scanner;

public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        int[] digit = new int[10];
        System.out.println("Enter a phonenumber with 10 digitos");
        Scanner numin = new Scanner(System.in);
        String numcatch = numin.nextLine();
        for (int i = 0; i < 10; i++) {
            digit[i] = Character.getNumericValue(numcatch.charAt(i));
        }
        //System.out.println(Arrays.toString(digit));
        
        System.out.println("Phonenumber is: (" + digit[0] + digit[1] + digit[2] + ") " + digit[3] + digit[4] + digit[5] + "-" + digit[6]
                + digit[7] + digit[8] + digit[9]);
    }
}
