/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package highlow;

import java.util.Arrays;

//import javax.management.ValueExp;

public class App {
    public String getGreeting() {
        return "Hello World!";

    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // String inputNum = "1 2 3 4 5";
        String inputNum = "1 2 -3 4 5";
        // String inputNum = "1 9 3 4 -5";

        int max, min = 0;

        String[] concat = inputNum.split(" ");

        int[] vector = new int[10];

        for (int i = 0; i <= concat.length; i++) {

            vector[i] = Integer.parseInt(concat[i]);

        }
        System.out.println(Arrays.toString(vector));

        for (int j = 0; j <= concat.length; j++) {

            if (vector[j] > max) {

                max = vector[j];
            }

            if (vector[j] < min) {
                min = vector[j];
            }
            

        }
        System.out.println("Max = " + max);
        System.out.println("Min = " + min);
    }
}
