/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package likes;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());

        // String[] likes = {};
        // String[] likes = { "Peter" };
        // String[] likes = {"Jacob", "Alex"};
        // String[] likes = {"Max", "John", "Mark"};
        String[] likes = { "Alex", "Jacob", "Mark", "Max" };

        System.out.println(likes.length + " likes");
        for (int i = 0; i < likes.length; i++) {

        }
        int elementnum = likes.length;

        switch (elementnum) {
            case 0:
                System.out.println("no one likes this");
                break;
            case 1:
                System.out.println(likes[0] + " likes this");
                break;
            case 2:
                System.out.println(likes[0] + " and " + likes[1] + " likes this");
                break;
            case 3:
                System.out.println(likes[0] + ", " + likes[1] + " and " + likes[2] + " likes this");
                break;
            default:
                System.out.println(likes[0] + ", " + likes[1] + " and " + (likes.length - 2) + " others likes this");
                break;
        }

    }

}
