/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package phonenumber;

import java.util.Arrays;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        int[] digit = new int[10];
        System.out.println("Introducir a continuacion un numero telefonico de 10 digitos");
        Scanner num = new Scanner(System.in);

        for (int i = 0; i < 10; i++) {
            digit[i] = num.nextInt();
        }

        System.out.println(Arrays.toString(digit));
        System.out.println("Numero telefonico: (" + digit[0] + digit[1] + digit[2] + ") " + digit[3] + digit[4] + digit[5] + "-" + digit[6]
                + digit[7] + digit[8] + digit[9]);
    }
}
