# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
    - name: Style Code Report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: CheckStyle
        path: build/reports/checkstyle/checkstyle.html
    - name: Build
      uses: actions/upload-artifact@v2
      with:
       name: Build
       path: build/distributions/